//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrarySchool
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestAppointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestAppointment()
        {
            this.ExecutionAttempts = new HashSet<ExecutionAttempt>();
        }
    
        public int ID { get; set; }
        public int Test { get; set; }
        public int StudentID { get; set; }
        public int Responsible { get; set; }
        public System.DateTime Time { get; set; }
        public System.DateTime DeadLine { get; set; }
        public byte LeadTime { get; set; }
        public byte AttemptCount { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExecutionAttempt> ExecutionAttempts { get; set; }
        public virtual Student Student { get; set; }
        public virtual Test Test1 { get; set; }
    }
}
