//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class answerOption
    {
        public int id { get; set; }
        public Nullable<int> questionId { get; set; }
        public string answerText { get; set; }
        public Nullable<bool> isCorect { get; set; }
    
        public virtual question question { get; set; }
    }
}
