//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class assignedTest
    {
        public int id { get; set; }
        public Nullable<int> testId { get; set; }
        public Nullable<int> atemptsAllowed { get; set; }
        public Nullable<int> assignedBy { get; set; }
        public Nullable<int> assignedTo { get; set; }
        public Nullable<int> assignedAt { get; set; }
    
        public virtual teacher teacher { get; set; }
        public virtual student student { get; set; }
        public virtual test test { get; set; }
    }
}
