//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestingSystemEntities : DbContext
    {
        public TestingSystemEntities()
            : base("name=TestingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<answerOption> answerOptions { get; set; }
        public virtual DbSet<assignedTest> assignedTests { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<groupSubject> groupSubjects { get; set; }
        public virtual DbSet<headTeacher> headTeachers { get; set; }
        public virtual DbSet<question> questions { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<subject> subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<teacherSubject> teacherSubjects { get; set; }
        public virtual DbSet<test> tests { get; set; }
        public virtual DbSet<testResult> testResults { get; set; }
    }
}
